# Generated by Django 4.2.4 on 2024-05-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "po_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "vendor_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendors.vendor_details",
                    ),
                ),
            ],
        ),
    ]
