# Generated by Django 4.2.4 on 2024-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("po", "0002_purchaseorder_acknowledgment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
