# Generated by Django 4.2.4 on 2024-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("po", "0003_alter_purchaseorder_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
