# Generated by Django 4.2.4 on 2024-05-04 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("on_time_delivery_rate", models.FloatField(null=True)),
                ("quality_rating_avg", models.FloatField(null=True)),
                ("average_response_time", models.FloatField(null=True)),
                ("fulfillment_rate", models.FloatField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendors.vendor_details",
                    ),
                ),
            ],
        ),
    ]
